### model
model_name_or_path: your_path/chatglm3-japanese-zero

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: query_key_value,dense_h_to_4h,dense_4h_to_h,dense
additional_target: word_embeddings,output_layer

### ddp
ddp_timeout: 180000000
deepspeed: config/deepspeed/ds_z2_config.json

### dataset
dataset: wikipedia_ja,aozorabunko_clean,wikipedia_zh,wikitext
cutoff_len: 1024
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataset_dir: data_for_model

### output
output_dir: your_path/step5_pt_lora
logging_steps: 100
save_steps: 10000
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.05
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 10000
